services:
  api:
    build: .
    container_name: notes_core_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/notes?sslmode=disable
    restart: unless-stopped
    networks:
      - notes_core_network

  db:
    image: postgres:16
    container_name: notes_core_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_core:/var/lib/postgresql/data
    networks:
      - notes_core_network

volumes:
  pgdata_core:

networks:
  notes_core_network:
    driver: bridge
